package cz.ich.notinoapp.feature.product.data.remote

import com.google.gson.annotations.SerializedName

/**
 * Class generated by Android studio.
 */
data class ProductResponse(
    @SerializedName("vpProductByIds")
    val vpProductByIds: List<VpProductById>
)

data class VpProductById(
    @SerializedName("annotation")
    val `annotation`: String,
    @SerializedName("attributes")
    val attributes: Attributes,
    @SerializedName("brand")
    val brand: Brand,
    @SerializedName("id")
    val id: String,
    @SerializedName("imageUrl")
    val imageUrl: String,
    @SerializedName("masterId")
    val masterId: Int,
    @SerializedName("name")
    val name: String,
    @SerializedName("orderUnit")
    val orderUnit: String,
    @SerializedName("price")
    val price: Price,
    @SerializedName("productId")
    val productId: Int,
    @SerializedName("reviewSummary")
    val reviewSummary: ReviewSummary,
    @SerializedName("stockAvailability")
    val stockAvailability: StockAvailability
)

data class Attributes(
    @SerializedName("EAN")
    val eAN: String,
    @SerializedName("Master")
    val master: Boolean,
    @SerializedName("Niche")
    val niche: Boolean,
    @SerializedName("PackageSize")
    val packageSize: PackageSize
)

data class Brand(
    @SerializedName("id")
    val id: String,
    @SerializedName("name")
    val name: String
)

data class Price(
    @SerializedName("currency")
    val currency: String,
    @SerializedName("value")
    val value: Int
)

data class ReviewSummary(
    @SerializedName("score")
    val score: Int
)

data class StockAvailability(
    @SerializedName("code")
    val code: String,
    @SerializedName("count")
    val count: Any?
)

data class PackageSize(
    @SerializedName("depth")
    val depth: Int,
    @SerializedName("height")
    val height: Int,
    @SerializedName("width")
    val width: Int
)